[project]
name = "llmengineering"
version = "0.1.0"
description = "Minimal Python project for LLM engineering."
authors = [
    { name = "Your Name", email = "your@email.com" }
]
requires-python = ">=3.11.7"

[tool.uv]
# UV-specific settings can be added here if needed
